# 网站图标
favicon:
  enable: true
  icon: /images/favicon.png
  touch_icon: /images/favicon.png

# 用户头像与昵称
avatar:
  author_photo: /images/avatar.png
  author_nickname: DudeGuuud
  path: /

# Google 分析
gtag:
  enable: false
  gtagkey: UA-xxxxxxx-x

# 文章评论系统
comments:
  enable: false

# 主题页面导航栏
navbar:
  -
    name: Home
    enable: true
    path: /
    key: home
  -
    name: Archives
    enable: true
    path: /archives/
    key: archives
  -
    name: Categories
    enable: true
    path: /categories/
    key: categories
  -
    name: Tags
    enable: true
    path: /tags/
    key: tags
  -
    name: Friends
    enable: false
    path: /friends/
    key: friends
  -
    name: About
    enable: true
    path: /about/
    key: about

# 文章目录
catalog:
  enable: true

# 文章末尾的上一页与下一页
prevnext:
  enable: true

# 友链详细信息：支持多个友链
friends:
  -
    nickname: GitHub
    site: https://github.com/DudeGuuud
    meta: My GitHub Profile

# 页脚信息
footer:
  social:
    -
      name: github
      icon: github
      path: https://github.com/DudeGuuud
    -
      name: rss
      icon: rss
      path: /rss.xml

  more:
    -
      name: Copyright © {thisYear} DudeGuuud
      path: https://github.com/DudeGuuud
    -
      name: Theme by Oranges | Powered by Hexo
      path: https://github.com/zchengsite/hexo-theme-oranges

  # 浏览量统计
  views:
    enable: false

# 文章搜索
search:
  enable: true
  placeholder: 搜索文章...

# 深/浅配色切换
colorSwitch:
  enable: true

# 文章分享
postShare:
  enable: true
  twitter:
    enable: true
  facebook:
    enable: true

# 代码块配置
codeBlock:
  style: 'normal'
  copy:
    enable: true

# MathJax Support
mathjax:
  enable: true

# 主题色
themeColor: '#ff6b35'
