menu:
  - name: Home
    url: /
  - name: Archives
    url: /archives
  - name: Categories
    url: /categories
  - name: Tags
    url: /tags
  - name: About
    url: /about
  - name: RSS
    url: /rss.xml
sidebar: # Sidebar
  enable: true 
  widgets:
    - search # Search
    - notice # Notice
    - categories # Categories
    - tags # Tags
    - links # Links

  numlimit: # Limit the number of items shown in the sidebar
    categories: 5
    tags: 10
    
  links:
    - name: b站主页
      url: https://space.bilibili.com/1515974075?spm_id_from=333.1387.fans.user_card.click
    - name: github主页
      url: https://github.com/m310ct
    - name: 电子邮箱
      url: mailto:0x310ct@gmail.com
  notice: # 公告栏内容
    enable: true # 设置为 true 启用，false 禁用
    content: "欢迎来到m310ct的博客，技术交流请联系我！" # 公告栏显示的内容

toc: #文章目录
  enable: true
