menu:
  - name: Home
    url: /
  - name: Archives
    url: /archives
  - name: Categories
    url: /categories
  - name: Tags
    url: /tags
  - name: About
    url: /about
  - name: RSS
    url: /rss.xml
sidebar: # Sidebar
  enable: true 
  widgets:
    - search # Search
    - notice # Notice
    - categories # Categories
    - tags # Tags
    - links # Links

  numlimit: # Limit the number of items shown in the sidebar
    categories: 5
    tags: 10
    
  links:
    - name: Bilibili
      url: https://space.bilibili.com/83007377
    - name: Github
      url: https://github.com/DudeGuuud
    - name: Email
      url: 2032635652@qq.com
  notice: # 公告栏内容
    enable: true # 设置为 true 启用，false 禁用
    content: "Feel free to contact me." # 公告栏显示的内容

toc: #文章目录
  enable: true
