name: 自动部署 Hexo

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [23.11.0]

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 记录开始时间
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: 缓存依赖
        uses: actions/cache@v4
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 安装依赖
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci

      - name: 记录安装时间
        run: |
          END_TIME=$(date +%s)
          echo "Install duration: $((END_TIME - START_TIME)) seconds"

      - name: 生成静态文件
        run: |
          ./node_modules/.bin/hexo clean
          ./node_modules/.bin/hexo generate

      - name: 记录生成时间
        run: |
          GEN_TIME=$(date +%s)
          echo "Generate duration: $((GEN_TIME - END_TIME)) seconds"

      - name: 检查 public 目录
        run: ls -la ./public

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          keep_files: true
